### PR TITLE
Option / Argument Manipulation

### PR DESCRIPTION
**Pull request by grmartin**
- Option/Argument Manipulation callback and documentation
- `spawn` debug wrapper and option.

### CODE REVIEW

**Comment by micahblu** [comment]
Hi @grmartin Thanks for the pull request! Could you please provide an example gulp task that makes use of the options?

**Comment by grmartin** [comment]
@micahblu Sure thing. I'll do so this afternoon.

**Comment by grmartin** [comment]
@micahblu Ready for Review.

**Comment by micahblu** [comment]
@grmartin thanks checking now

**Comment by micahblu** [comment]
I've confirmed it working but I'm having some trouble getting it to past in a mocha test. Could you add a test please?

**Comment by grmartin** [comment]
@micahblu Ready for Review.

**Comment by micahblu** [comment]
@grmartin Thanks! So I'm seeing the same error I saw when I added the mocha test and ran it. Here's my output: 

```
➜  gulp-connect-php git:(grmartin-grmartin/manipulation-callbacks) mocha
  gulp-connect-php
PHP 5.6.30 Development Server started at Fri Apr 14 12:51:44 2017
Listening on http://127.0.0.1:8000
Document root is /Volumes/WorkSpace/Projects/gulp-connect-php
Press Ctrl-C to quit.
[Fri Apr 14 12:51:44 2017] 127.0.0.1:63386 [404]: / - No such file or directory
[Fri Apr 14 12:51:44 2017] 127.0.0.1:63387 [200]: /test/fixtures/hello.php
[Fri Apr 14 12:51:45 2017] 127.0.0.1:63388 [404]: / - No such file or directory
[Fri Apr 14 12:51:45 2017] 127.0.0.1:63389 [200]: /test/fixtures/hello.php
    ✓ Should start a basic php server (356ms)
exec error: Error: Command failed: lsof -i :8000

    1) Should start a basic php server, with a set environment variable and updated memory limits set via the configCallback option


  1 passing (393ms)
  1 failing

  1) gulp-connect-php Should start a basic php server, with a set environment variable and updated memory limits set via the configCallback option:
     Uncaught TypeError: Cannot read property '1' of null
      at index.js:55:48
      at ChildProcess.exithandler (child_process.js:218:5)
      at maybeClose (internal/child_process.js:885:16)
      at Socket.<anonymous> (internal/child_process.js:334:11)
      at Pipe._handle.close [as _onclose] (net.js:501:12)
```

**Comment by grmartin** [comment]
That's really strange. It's passing on my local machine, I would not have committed it otherwise. Can you tell me exactly how you were invoking Mocha? And maybe Node version? I've just left for the grocery store but I'll be happy to dig in when I return and the baby is asleep. ... I'm on a mac with the latest Node and mostly running Mocha via PhpStorm.

**Comment by grmartin** [comment]
Index.js:55 implies that the lsof failure above is blowing up the test.

**Comment by grmartin** [comment]
@micahblu but then again, I'm just poking around in an iPhone from the passenger compartment of a car. So I could be off base (small screen and all)

**Comment by micahblu** [comment]
@grmartin ok, I'll take a closer look.

**Comment by micahblu** [comment]
@grmartin I see the issue and it appears to be unrelated to this pr. Merging now. Thanks for the good work!

**Pull request merged**
