### PR TITLE
Node 4 support added back.

### LINKED ISSUE #42: Crash when running version 1.0.0
Hi!

All the examples crash when run.
Installation of version 0.0.8 does not give errors when run using the same examples.

<project>/node_modules/gulp-connect-php/index.js:16
    [...arguments].forEach((x) => { this[x] = Symbol(x) });
     ^^^
SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/raymond/Google Drive/sites/bolwerkenschede/gulpfile.js:5:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

environment: mac osx sierra

### PR DESCRIPTION
**Pull request by grmartin**
- Node 4 Support with Accompanying Babel conversion, and test suite.
- NPM5 lock file

This should resolve https://github.com/micahblu/gulp-connect-php/issues/42 however, it shouldnt be merged until i have 1 or more approvals from people trying to use it on Node 4.

@focussing or @MiguelDebruyne if either of you wouldnt mind trying this in response to Issue 42, id appreciate it... Let us know how it goes here or in the ticket place.

### CODE REVIEW

**Comment by MiguelDebruyne** [comment]
Alright, cool! I couldn't make it work even with an older node version. Granted, I didn't had enough time to solve it so I dropped it. I'll check it out this week and report back to you.

**Comment by mathiasmadsen** [comment]
I experienced the same error as in #42 and tried this version instead. However, it seems the gulpfile ignores gulp-connect-php completely, as it looks for the task 'default' now:

From the terminal:
`Task 'default' is not in your gulpfile`

My gulpfile:

```
var gulp = require('gulp'),
    connect = require('gulp-connect-php'),
    browserSync = require('browser-sync'),
    sass        = require('gulp-sass');


gulp.task('connect-sync', function() {
  connect.server({
    base: 'app',
    port: 4000
  }, function (){
    browserSync({
      injectChanges: true,
      proxy: '127.0.0.1:4000'
   });
  });

  gulp.start('sass');
  gulp.start('watch');

});

```

**Comment by ghost** [comment]
I have that error: 
```
/home/ae_mc/Документы/sites/node_modules/gulp-connect-php/index.js:16
    [...arguments].forEach((x) => { this[x] = Symbol(x) });
     ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ae_mc/Документы/sites/gulpfile.js:2:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```
on node v4.2.6.
That's gulpgile.js:
```
var gulp = require('gulp'),
    connect = require('gulp-connect-php'),
    browserSync = require('browser-sync');

gulp.task('connect-sync', function() {
  connect.server({}, function (){
    browserSync({
      proxy: '127.0.0.1:8000'
    });
  });

  gulp.watch('**/*.php').on('change', function () {
    browserSync.reload();
  });
});
```
That's package.json:
```
{
  "name": "myserver",
  "version": "1.0.0",
  "description": "My First Server with Gulp",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Ae_Mc",
  "license": "ISC",
  "devDependencies": {
    "browser-sync": "^2.23.6",
    "gulp": "^3.9.1",
    "gulp-connect-php": "^1.0.1",
    "gulp-sass": "^3.1.0"
  }
}

```
What's wrong?

**Comment by grmartin** [comment]
@creeperasha it looks like Node is ignoring the directive to import the index-compat.js file, can you verify that it is there? Perhaps send me the package file from your installed version of this module?

**Comment by ghost** [comment]
Where should it be?

**Comment by grmartin** [comment]
In your example: `/home/ae_mc/Документы/sites/node_modules/gulp-connect-php/package.json`

**Comment by ghost** [comment]
That's my project folder:
https://yadi.sk/d/G-ZOO9G23SnNAN

**Comment by ghost** [comment]
That's packaje.json:
```
{
  "_args": [
    [
      "gulp-connect-php",
      "/home/ae_mc/Документы/sites"
    ]
  ],
  "_from": "gulp-connect-php@latest",
  "_id": "gulp-connect-php@1.0.1",
  "_inCache": true,
  "_installable": true,
  "_location": "/gulp-connect-php",
  "_nodeVersion": "7.2.0",
  "_npmOperationalInternal": {
    "host": "packages-18-east.internal.npmjs.com",
    "tmp": "tmp/gulp-connect-php-1.0.1.tgz_1494186110959_0.15178385260514915"
  },
  "_npmUser": {
    "email": "micahblu@gmail.com",
    "name": "micahblu"
  },
  "_npmVersion": "3.10.9",
  "_phantomChildren": {},
  "_requested": {
    "name": "gulp-connect-php",
    "raw": "gulp-connect-php",
    "rawSpec": "",
    "scope": null,
    "spec": "latest",
    "type": "tag"
  },
  "_requiredBy": [
    "#DEV:/"
  ],
  "_resolved": "https://registry.npmjs.org/gulp-connect-php/-/gulp-connect-php-1.0.1.tgz",
  "_shasum": "0da0c50ba0a31ad50e2480b6bd05713d27f27808",
  "_shrinkwrap": null,
  "_spec": "gulp-connect-php",
  "_where": "/home/ae_mc/Документы/sites",
  "author": {
    "name": "micahblu"
  },
  "bugs": {
    "url": "https://github.com/micahblu/gulp-php/issues"
  },
  "dependencies": {
    "bin-version-check": "^2.1.0",
    "opn": "^1.0.0"
  },
  "description": "Starts a php server",
  "devDependencies": {
    "mocha": "^3.2.0",
    "supertest": "^3.0.0"
  },
  "directories": {},
  "dist": {
    "shasum": "0da0c50ba0a31ad50e2480b6bd05713d27f27808",
    "tarball": "https://registry.npmjs.org/gulp-connect-php/-/gulp-connect-php-1.0.1.tgz"
  },
  "engines": {
    "node": ">=5.0.0"
  },
  "gitHead": "e6c9058ddb0faa51455cf157e6bbaa548bb50d05",
  "homepage": "https://github.com/micahblu/gulp-connect-php#readme",
  "keywords": [
    "connect",
    "gulp",
    "php",
    "server"
  ],
  "license": "MIT",
  "main": "index.js",
  "maintainers": [
    {
      "name": "grmartin",
      "email": "grmartin@martinfamily.email"
    },
    {
      "name": "micahblu",
      "email": "micahblu@gmail.com"
    }
  ],
  "name": "gulp-connect-php",
  "optionalDependencies": {},
  "readme": "ERROR: No README data found!",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/micahblu/gulp-connect-php.git"
  },
  "scripts": {
    "test": "mocha ./test"
  },
  "version": "1.0.1"
}
```

**Comment by Creeperasha** [comment]
Thanks for the quick response!

**Comment by grmartin** [comment]
This is version `1.0.1` of the library. That version was broken on 4.x and requires me 5.x. Version 1.0.2 fixed what we lost in the rewrite and added back 4.x support. Which appears to never have been pushed. If you need it now you can pull this as a git repo in your project and I’ll speak to @micahblu  about getting it pushed to npm.

**Comment by ghost** [comment]
Thanks!

**Pull request merged**
